version: '2'

# The build-args have default values that will be used if unspecified. 
services:
    jenkins:
        image: jenkinsci/blueocean
        volumes:
            - ./jenkins_home:/var/jenkins_home
        environment:
            - DOCKER_HOST=tcp://socat:2375
        links:
            - socat
        ports:
            - "8080:8080"

    socat:
        image: bpack/socat
        command: TCP4-LISTEN:2375,fork,reuseaddr UNIX-CONNECT:/var/run/docker.sock
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        expose:
            - "2375"
